name: github pages

on:
  push:
    branches:
      - master

env:
  REACT_APP_CONTENTFUL_SPACE: ${{ secrets.REACT_APP_CONTENTFUL_SPACE }}
  REACT_APP_CONTENTFUL_ACCESSTOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESSTOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: yarn && yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          cname: axelniklasson.se
